### ISSUE TITLE
[Bug]: Unexpected exception when trying to connect to an environment

### ISSUE THREAD

**Issue by ericregnier** [Power-Maverick/DataverseDevTools-VSCode#47]
### Contact Details

e.regnier@gmail.com

### What happened?

**Repro steps:**
1. Install latest version of Dataverse DevTools
2. Setup new connection with username/password auth type
3. Try to connect

**Actual results:**
Error popup stating to open a bug on github. I tried in different environments in two different tenants.

**Date & Time as requested**
11/01/2022 around 9:30am **NZT**

### What version of the tool are you using?

v1.1.11

### What version of Visual Studio Code are you running?

1.63.2

### Relevant log output

```shell
[Extension Host] Bad Request
Dataverse DevTools: Error occured. Please report it on GitHub with the activity you tried to perform along with Date & Time.
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
fire @ event.ts:577
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
(anonymous) @ mainThreadMessageService.ts:86
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:472
_invokeHandler @ rpcProtocol.ts:457
_receiveRequest @ rpcProtocol.ts:373
_receiveOneMessage @ rpcProtocol.ts:295
(anonymous) @ rpcProtocol.ts:160
fire @ event.ts:577
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:958
(anonymous) @ ipc.net.ts:831
fire @ event.ts:577
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
P @ ipc.net.ts:60
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
```

**Comment by Power-Maverick** [comment]
Couldn't find any error log during that time. Did you validate if username/password was correct? Also, is MFA enabled on your environment? If so, try using i) Microsoft Login Prompt OR ii) Client Id/Secret for connection.
Let me know how it goes.

**Comment by ericregnier** [comment]
Yes, and using that account regularly. Am able to connect to other tools like XrmToolBox, PIT successfully. I'm using the login prompt. Happy to have a session to show live...

**Comment by Power-Maverick** [comment]
I was testing something on my end; which is now fixed so Username Password authentication should now be working.

**Comment by ericregnier** [comment]
Hi @Power-Maverick, sorry to be a bugger but this is still happening with the latest version (2.0.2). I've forced uninstalled and reinstalled it.
